### PR TITLE
feat: move CRD to folder, following helm best practices

### PR DESCRIPTION
**Pull request by fernandezcuesta**
According to [helm best practices](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/) the CRD can be specified by a `crds` folder. In this case, a symlink to the `kube/crd` folder would be more convenient to have a single source of truth for the CRD.

### CODE REVIEW

**Comment by AbdelrhmanHamouda** [comment]
Hello @fernandezcuesta, 
Thank you for your contribution and keenness on having the project follow the best practises. It is defiantly something that is aligned with the project. 

This PR is taking a bit of time to merge is because i want to test and see if this change may have a negative impact on the release workflow since i don't know how it would react to symlinks

**Comment by AbdelrhmanHamouda** [comment]
Hello @fernandezcuesta, 
In my preliminary testing, i am noticing that we are losing the check about `if .Values.k8s.customResourceDefinition.deploy` is set to deploy the CRD and other wise no. Is there a way to maintain this functionality and align with the best practises?

**Comment by AbdelrhmanHamouda** [comment]
@fernandezcuesta thanks again for the contribution and your patience with me on this! 

if it is okay with you, i would like to merge your changes but the branch has some conflicts with the master branch. Can you kindly resolve them so i can merge?

**Comment by jachinte** [comment]
@AbdelrhmanHamouda @fernandezcuesta Is it me or this PR introduced a regression?

```
java.nio.file.NoSuchFileException: charts/locust-k8s-operator/templates/crd-locusttest.yaml
```

Failing tests:

```
[LocustTestReconcilerTests](file:///.../locust-k8s-operator/build/reports/tests/test/classes/com.locust.operator.controller.LocustTestReconcilerTests.html). [Functional: Reconcile - cleanup onDelete event](file:///.../locust-k8s-operator/build/reports/tests/test/classes/com.locust.operator.controller.LocustTestReconcilerTests.html#cleanupOnDeleteEvent())
[LocustTestReconcilerTests](file:///.../locust-k8s-operator/build/reports/tests/test/classes/com.locust.operator.controller.LocustTestReconcilerTests.html). [Functional: Reconcile - onAdd event](file:///.../locust-k8s-operator/build/reports/tests/test/classes/com.locust.operator.controller.LocustTestReconcilerTests.html#reconcileOnAddEvent())
[LocustTestReconcilerTests](file:///.../locust-k8s-operator/build/reports/tests/test/classes/com.locust.operator.controller.LocustTestReconcilerTests.html). [Functional: Reconcile - NOOP to onUpdate event](file:///.../locust-k8s-operator/build/reports/tests/test/classes/com.locust.operator.controller.LocustTestReconcilerTests.html#reconcileOnUpdateEvent())
```

This is what I'm running: `./gradlew check`.

**Comment by jachinte** [comment]
@AbdelrhmanHamouda I've fixed this in #97

**Comment by AbdelrhmanHamouda** [comment]
@jachinte thanks for catching this. This also exposed a relation that i wasn't taken into account in triggering the CI builds. I will address this in the future.

**Pull request merged**
